[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
Numlock=on
InputMethod=

[Theme]
#Current=breeze
Current=arcolinux-simplicity
CursorTheme=Bibata-Modern-Ice
Font=Noto Sans,10,-1,0,50,0,0,0,0,0

[Users]
HideShells=/usr/bin/nologin,/bin/false
MaximumUid=60000
MinimumUid=1000

[Autologin]
Enable=true
User=vcatafesta
Relogin=false
#Session=plasma.desktop

